"""Build reproducible Roblox templates and rig metadata from verified Studio imports."""
import json
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, indent, tostring
ROOT = Path(__file__).resolve().parents[2]
imports = json.loads((ROOT/'assets/guards/studio-imports.json').read_text())
def lua(v):
    if isinstance(v, dict): return '{'+','.join('['+json.dumps(k)+']='+lua(x) for k,x in v.items())+'}'
    if isinstance(v, list): return '{'+','.join(lua(x) for x in v)+'}'
    if v is None: return 'nil'
    return json.dumps(v)
def prop(p, typ, name, val):
    e=SubElement(p,typ,name=name)
    if isinstance(val,dict):
        for k,v in val.items(): SubElement(e,k).text=str(v)
    else: e.text=str(val)
    return e
catalog={}
for key,data in imports.items():
    report=json.loads((ROOT/f'assets/guards/{key}/{key}-report.json').read_text())
    assert {p['name'] for p in data['parts']} == set(report['parts']), key
    catalog[key]={k:report[k] for k in ('label','tier','height','parts','bones','palette')}
    # Meshes retain their imported frame (-Z forward); GuardVisual normalizes once.
    root=Element('roblox',version='4')
    model=SubElement(root,'Item',{'class':'Model','referent':'model'})
    prop(SubElement(model,'Properties'),'string','Name',key)
    for i,part in enumerate(data['parts']):
        assert not part['surface'] and not part['texture'], 'review textured import'
        item=SubElement(model,'Item',{'class':'MeshPart','referent':f'p{i}'})
        p=SubElement(item,'Properties')
        prop(p,'string','Name',part['name'])
        prop(p,'Content','MeshId',{'url':part['mesh']})
        prop(p,'Vector3','size',dict(zip(('X','Y','Z'),part['size'])))
        prop(p,'Vector3','InitialSize',dict(zip(('X','Y','Z'),part['meshSize'])))
        prop(p,'CoordinateFrame','CFrame',dict(zip(('X','Y','Z','R00','R01','R02','R10','R11','R12','R20','R21','R22'),part['cf'])))
        for n,v in [('Anchored','true'),('CanCollide','false'),('CanTouch','false'),('CanQuery','false')]: prop(p,'bool',n,v)
    indent(root)
    (ROOT/f'src/ServerStorage/GuardTemplates/{key}.rbxmx').write_text(tostring(root,encoding='unicode'))
(ROOT/'src/ReplicatedStorage/Shared/GuardCatalog.luau').write_text('-- Generated by blender/guards/build_runtime_assets.py; source mesh roles and bone pivots.\nreturn '+lua(catalog)+'\n')
p=ROOT/'default.project.json'; project=json.loads(p.read_text());project['tree']['ServerStorage']={'$className':'ServerStorage','$ignoreUnknownInstances':True,'GuardTemplates':{'$path':'src/ServerStorage/GuardTemplates'}};p.write_text(json.dumps(project,indent=2)+'\n')
print('Generated eight templates and complete rig metadata')
