"""Build the fantasy concept handoff. Does not touch runtime source."""
from pathlib import Path
import json
from html import escape

ROOT = Path(__file__).resolve().parent
rows = [
 ('mushroom','Toadstool Cottage',250000,'Rare',26,24,14,1,'cozy','Round stalk room; trophy alcove and short shelf.','Ground-level round doorway.','Moss-coloured path with pale stepping stones.','A little room under a very big hat.'),
 ('treehouse','The Treehouse',750000,'Rare',38,34,30,1,'cozy','One enclosed cabin above a deck; collection shelf along its rear wall.','Continuous guarded stairs to the deck; rope ladder is decorative.','Warm timber path to the stair foot.','Finally, a place above all the drama.'),
 ('slime','Gloop House',2500000,'Epic',34,30,18,1,'modern','Green slime walls inside and out, oversized goo lobes, green display recesses; stable level floor.','Fixed plum doorway and dry floor; goo stays outside the route.','Green puddle border around a dry contrasting path.','A little messy. Entirely yours.'),
 ('raven','Raven’s Rest',8000000,'Epic',38,32,26,2,'classic','Charcoal-black two-floor raven house with folded-wing roof and upper trophy gallery.','Ground-level arched door and interior dogleg stair inside the broad body.','Charcoal slabs with graphite edges along an even walking strip.','A little mystery. A lot of room to roost.'),
 ('crystal','Crystal Spire',25000000,'Legendary',38,34,45,2,'modern','Two broad usable levels inside the base/core; thin spires are decorative.','Door in rock base; stair within the central volume.','Dark stone-coloured slabs with violet edge insets.','Your collection, with a sharper skyline.'),
 ('galleon','The Beached Galleon',150000000,'Legendary',48,48,50,2,'classic','Lower hull gallery and raised stern cabin, linked by stairs.','Front gangplank to deck and broad companionway into cabin.','Plank approach aligned with a guarded gangplank.','Retired from sailing. Still collecting treasure.'),
 ('dragon',"Dragon's Roost",300000000,'Legendary',48,44,40,2,'royal','Stone hoard hall and upper display balcony inside the cone.','Cave door with clear route past gold piles; internal stair.','Obsidian-coloured pavers with orange inset edges.','The roof comes with a very sleepy tenant.'),
 ('skyisland','Sky Islands',600000000,'Legendary',54,50,55,2,'royal','Two-floor main home; small outdoor viewing platforms on satellites.','Stationary stair route from ground, then guarded bridges.','Pale path to a grounded stone stair support.','A home with a little less ground beneath it.'),
 ('goldenpig','The Golden Piggy',1000000000,'Legendary',56,44,40,2,'royal','Belly vault hall below; upper gallery and snout bay-window lounge.','Belly door and internal stairs to ear balconies; coin-slot skylight.','Flat gold coin pavers along an even walkable strip.','You saved so much, you moved into the pig.'),
]
fields=('id','name','cost','rarity','width','depth','height','accessibleFloors','finishFamily','interior','access','drive','blurb')
houses=[]
for row in rows:
    h=dict(zip(fields,row))
    h.update(status='concept',dimensionsStatus='proposed complete envelope, not measured',measuredPartCount=None,measuredFootprint=None,
             buildRoute='procedural visual geometry; Fable runtime integration',motionAuthored=False)
    h['idStatus'] = 'proposed replacement ID; Fable registry alignment pending' if h['id']=='raven' else 'fixed in HOUSE-TIER-BRIEF.md'
    houses.append(h)
(ROOT/'catalogue.json').write_text(json.dumps(houses,indent=2),encoding='utf-8')
table='\n'.join(f"<tr><td><code>{h['id']}</code><br><strong>{escape(h['name'])}</strong></td><td>{h['cost']:,}<br>{h['rarity']}</td><td>{h['width']} × {h['depth']} × {h['height']}<br>{h['accessibleFloors']} accessible floor(s)</td><td>{escape(h['access'])}</td></tr>" for h in houses)
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fantasy houses · first concept pass</title><style>
*{box-sizing:border-box}body{margin:0;background:#faf3e5;color:#30271f;font:16px/1.5 'Trebuchet MS',Arial,sans-serif}main{max-width:1320px;margin:auto;padding:44px 26px}h1{font-size:clamp(38px,5vw,66px);letter-spacing:-.045em;line-height:1.05;max-width:900px;margin:12px 0 20px}h2{font-size:28px;margin:12px 0}p{max-width:820px;color:#625443}.eyebrow{color:#456244;letter-spacing:.13em;font-size:12px;font-weight:bold;text-transform:uppercase}a{color:#285740;text-underline-offset:4px}nav{display:flex;gap:22px;flex-wrap:wrap;margin:24px 0}figure{margin:30px 0;background:white;border:1px solid #d8cbb5;border-radius:15px;overflow:hidden}figure img{display:block;width:100%;height:auto}figcaption{padding:16px 20px;font-size:14px;color:#625443}.notice{border-left:4px solid #456244;background:#eee6d5;padding:18px 22px;margin:25px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.grid figure{margin:0}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px;min-width:650px}th,td{text-align:left;padding:15px 12px;border-bottom:1px solid #d8cbb5;vertical-align:top}th{color:#456244}section{margin-top:48px}footer{border-top:1px solid #d8cbb5;margin-top:42px;padding-top:20px;color:#625443;font-size:13px}@media(max-width:800px){.grid{grid-template-columns:1fr}main{padding:28px 16px}}
</style></head><body><main><div class="eyebrow">Phase 4b · Fantasy direction · First concept pass</div><h1>Climbing out of the ordinary.</h1><p>Nine unmistakable shapes, from a modest toadstool to a colossal golden piggy bank. The new brief preserves the prices and ownership IDs of existing houses, and replaces the nine proposed realistic additions.</p><nav><a href="HANDOFF.md">Design handoff</a><a href="catalogue.json">Nine-house data</a><a href="prompts.json">Exact image prompts</a><a href="../rooms/REVISION-WALK-IN.md">Walk-in interior direction</a></nav><div class="notice"><strong>Real doors. Real rooms.</strong> Houses remain part of the shared street. Their interior size and condition progress with the house; stairs connect accessible floors. The older separate-room wording has not been adopted.</div><figure><a href="fantasy-lineup.png"><img src="fantasy-lineup.png" alt="Nine fantasy house silhouettes in price order"></a><figcaption>Nine-house visual lineup. Relative scale is illustrative; the numerical height targets below govern the measured model pass.</figcaption></figure><section><div class="eyebrow">First build candidates · 250K and 750K</div><h2>Start small, then climb.</h2><div class="grid"><figure><a href="toadstool-cottage-concept.png"><img src="toadstool-cottage-concept.png" alt="Toadstool cottage exterior, front and walk-in interior concept"></a><figcaption><strong>mushroom · Toadstool Cottage · 250K</strong><br>One cozy room inside the stalk, framed round openings and raised cap spots. Simple ground-level access.</figcaption></figure><figure><a href="treehouse-concept.png"><img src="treehouse-concept.png" alt="Treehouse exterior and cabin concept with stairs from the ground"></a><figcaption><strong>treehouse · The Treehouse · 750K</strong><br>A timber cabin and display deck within one oak. Main access uses stairs; the rope ladder is a decorative detail.</figcaption></figure></div></section><section><h2>The full ladder</h2><p>All bounds and floor counts are design targets. Width and depth must include canopy, bridges and access structures. Measured part counts and footprint checks are pending.</p><div class="table-wrap"><table><thead><tr><th>House / stable ID</th><th>Price / rarity</th><th>Target W × D × H (studs)</th><th>Physical access</th></tr></thead><tbody>__TABLE__</tbody></table></div></section><footer>Draft concepts, not approved Roblox models. Next: select the visual direction, then resolve measured starter layouts and geometry. No runtime source, live economy, Studio place or shared planning documents changed by this pass.</footer></main></body></html>'''
page=page.replace('<main>', '<main><div class="notice"><strong>Superseded in part:</strong> <a href="../fantasy-v3/index.html">Open the latest six-house concepts and Legendary animation study.</a> Raven, dragon, sky islands and the 1B Golden Piggy purchase have been replaced by the new brief.</div>',1)
page=page.replace('fantasy-lineup.png','fantasy-lineup-v2.png')
page=page.replace('<h2>The full ladder</h2>', '''<div class="eyebrow">User revision · More slime, no seasonal gingerbread</div><h2>Black feathers and green gloop.</h2><div class="grid"><figure><a href="raven-concept.png"><img src="raven-concept.png" alt="Raven’s Rest all-black fantasy house concept"></a><figcaption><strong>Raven’s Rest · 8M · replacement proposal</strong><br>Charcoal walls, folded-wing roof and a raven-shaped tower. Gingerbread is seasonal; the proposed raven ID needs registry alignment.</figcaption></figure><figure><a href="gloop-house-concept.png"><img src="gloop-house-concept.png" alt="Gloop House with green slime walls and thick dripping eaves"></a><figcaption><strong>slime · Gloop House · 2.5M</strong><br>Green inside and out, bulging goo corners and chunky slime window frames. A flat walking floor keeps the interior usable.</figcaption></figure></div></section><section><h2>The full ladder</h2>''')
page=page.replace('nine proposed realistic additions.', 'nine proposed realistic additions. Gingerbread is now reserved for seasonal content; Raven’s Rest is the proposed all-black replacement at 8M.')
(ROOT/'index.html').write_text(page.replace('__TABLE__',table),encoding='utf-8')
print('Built fantasy handoff data and gallery.')
