"""Local visual gallery; does not modify runtime game files."""
from pathlib import Path
import json
import html

root = Path(__file__).resolve().parent
houses = json.loads((root/'houses/catalogue-design.json').read_text())
cards = []
for house in houses:
    if house['existing']:
        continue
    name = html.escape(house['name'])
    price = f"{house['price']:,}"
    cards.append(f'''<article><a href="houses/{house['id']}.png"><img loading="lazy" src="houses/{house['id']}.png" alt="{name} exterior concept"></a><div class="caption"><span>{house['rarity'].upper()} · {price} COINS</span><h3>{name}</h3><p>Proposed envelope {house['width']} × {house['depth']} studs · {house['storeys']} visible levels.<br>Interior fit and final geometry pending.</p></div></article>''')
page = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>House catalogue · design review</title><style>
:root{--ink:#302820;--cream:#fbf4e7;--muted:#675846;--green:#244c3d;--line:#d9cbb6}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:var(--ink);font:16px/1.5 'Trebuchet MS',Arial,sans-serif}main{max-width:1240px;margin:auto;padding:48px 28px}header{padding-bottom:34px;border-bottom:2px solid var(--ink)}.eyebrow{font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:var(--green)}h1{font-size:clamp(36px,5vw,64px);line-height:1.02;letter-spacing:-.045em;max-width:780px;margin:16px 0}h2{font-size:32px;letter-spacing:-.025em;margin:0}h3{font-size:22px;margin:4px 0 8px}p{color:var(--muted);max-width:780px}a{color:var(--green);text-underline-offset:4px}nav{display:flex;gap:12px;flex-wrap:wrap;margin-top:25px}.button{display:inline-block;padding:12px 20px;background:var(--green);color:white;border-radius:9px;text-decoration:none;font-weight:bold}.outline{background:transparent;color:var(--green);box-shadow:inset 0 0 0 1px var(--green)}section{margin-top:48px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:wrap;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.rooms{grid-template-columns:repeat(2,minmax(0,1fr))}article{background:white;border:1px solid var(--line);border-radius:15px;overflow:hidden}article img{display:block;width:100%;aspect-ratio:1.15;object-fit:contain;background:#f5f3ef}article a{display:block}.rooms img{aspect-ratio:1.35}.caption{padding:20px}.caption span{font-size:11px;letter-spacing:.08em;font-weight:900;color:var(--green)}.caption p{font-size:14px;margin:8px 0 0}.note{border-left:4px solid var(--green);padding:15px 20px;background:#eee7d8;margin-top:24px}.shop{display:grid;grid-template-columns:1.4fr 1fr;align-items:center;gap:24px}.shop img{width:100%;border-radius:12px;border:1px solid var(--line)}footer{border-top:1px solid var(--line);margin-top:50px;padding-top:20px;font-size:13px;color:var(--muted)}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.rooms,.shop{grid-template-columns:1fr}}@media(max-width:480px){main{padding:28px 16px}.grid{grid-template-columns:1fr}}
</style></head><body><main><header><div class="eyebrow">Phase 4b · September 16 · visual review</div><h1>A home worth<br>working towards.</h1><p>A larger house should feel like an upgrade from the moment you walk through its door: more space, better finishes, and more of your story on display.</p><nav><a class="button" href="ui/catalogue.html">Try the house shop</a><a class="button outline" href="#interiors">Walk-in interiors</a><a class="button outline" href="#exteriors">Nine new houses</a><a class="button outline" href="README.md">Handoff status</a></nav></header>
<section id="interiors"><div class="section-head"><div><div class="eyebrow">4b.5 · updated direction</div><h2>Small beginnings. Room to grow.</h2></div><a href="rooms/REVISION-WALK-IN.md">Interior handoff</a></div><p>Real rooms within each house in the shared world. A door, a walkable floor and stairs where the house has more than one accessible level. These new concepts supersede the separate-room studies.</p><div class="grid rooms"><article><a href="rooms/starter-walk-in.png"><img src="rooms/starter-walk-in.png" alt="Dingy starter shack with patched walls and a small trophy shelf"></a><div class="caption"><span>STARTER · ONE SMALL ROOM</span><h3>Scruffy, warm, and yours.</h3><p>Patched panels, worn timber colours, simple furniture and a modest trophy shelf. The clear 16 × 12-stud interior shown is a design target, not a verified measurement.</p></div></article><article><a href="rooms/manor-walk-in.png"><img src="rooms/manor-walk-in.png" alt="Manor cutaway with stairs connecting the entrance to an upstairs trophy gallery"></a><div class="caption"><span>MANOR · TWO CONNECTED FLOORS</span><h3>A proper collection gallery.</h3><p>A welcoming ground floor and a dedicated upstairs display. The model stage must resolve the stair opening, landing and camera clearance.</p></div></article></div><div class="note"><strong>Your collection stays yours.</strong> Smaller houses show a selection; larger houses have more physical display space. A proposed achievement board/book keeps the full record available in every home.</div></section>
<section><div class="section-head"><div><div class="eyebrow">4b.3 · interactive prototype</div><h2>Choose the house you want.</h2></div><a href="ui/HANDOFF.md">UI handoff</a></div><div class="shop"><a href="ui/catalogue.html"><img src="review/phone-546.png" alt="Responsive Home shop with individually purchasable house cards"></a><div><h3>18 houses. Five clear states.</h3><p>Price order with All, Owned and Affordable filters. Owned homes offer Move In; capacity-limited homes explain Grow Your Pig. The full card is the tap target.</p><a class="button" href="ui/catalogue.html">Open interactive prototype</a><p>Local demo only. Existing houses use schematic placeholders; new houses use concept artwork. Native Roblox wiring and complete Home-page touch testing remain pending.</p></div></div></section>
<section id="exteriors"><div class="section-head"><div><div class="eyebrow">4b.4 · concept catalogue</div><h2>Nine new silhouettes.</h2></div><a href="houses/HANDOFF.md">Exterior specifications</a></div><p>Six new studies plus the three earlier concepts. Prices and dimensions are proposals for the final registry. Exterior levels do not automatically mean that every floor is furnished.</p><div class="grid">__CARDS__</div><div class="note">These are concept images, not Roblox models. Final builds still need physical walk-in floorplans, measured bounds and part counts, flat-colour materials, and a street-level visual check.</div></section><footer>GPT visual package · Fable runtime integration · No runtime scripts or published place changed by this package. Exact prompts and browser review reports are included alongside the handoffs.</footer></main></body></html>'''
page = page.replace('<header>', '<header><div class="note"><strong>New fantasy direction:</strong> this earlier catalogue is superseded. <a href="fantasy-v3/index.html">Open the current fantasy concepts</a>. The shop demo below remains a layout reference; its new-house IDs are obsolete.</div>', 1)
(root/'index.html').write_text(page.replace('__CARDS__', '\n'.join(cards)), encoding='utf-8')
print('Built visual gallery.')
