"""Validate imported bounds and write checked-in Rojo templates; no uploads."""
import json
from pathlib import Path
from xml.etree.ElementTree import Element,SubElement,tostring
ROOT=Path(__file__).resolve().parents[1]
folder=ROOT/'assets/environment/piggy-meadows/build-v1'
catalog=json.loads((folder/'catalog.json').read_text());imports=json.loads((folder/'mesh-import.json').read_text())
assert {p['name'] for p in imports}==set(catalog['parts'])
xml=Element('roblox',version='4');model=SubElement(xml,'Item',{'class':'Folder','referent':'MeadowTemplates'})
SubElement(SubElement(model,'Properties'),'string',name='Name').text='MeadowTemplates'
def prop(parent,kind,name,value):SubElement(parent,kind,name=name).text=str(value)
for p in imports:
    spec=catalog['parts'][p['name']]
    assert all(abs(a-b)<.002 for a,b in zip(spec['size'],p['size'])),p['name']
    corrected=[-p['position'][0],p['position'][1],-p['position'][2]]
    assert all(abs(a-b)<.002 for a,b in zip(spec['center'],corrected)),p['name']
    props=SubElement(SubElement(model,'Item',{'class':'MeshPart','referent':p['name']}),'Properties')
    prop(props,'string','Name',p['name'])
    for name,value in [('MeshId',p['meshId']),('TextureID',p['textureId'])]:SubElement(SubElement(props,'Content',name=name),'url').text=value
    for name,size in [('size',spec['size']),('InitialSize',p['size'])]:
        element=SubElement(props,'Vector3',name=name)
        for axis,v in zip('XYZ',size):SubElement(element,axis).text=str(v)
    frame=SubElement(props,'CoordinateFrame',name='CFrame')
    for axis,v in zip('XYZ',spec['center']):SubElement(frame,axis).text=str(v)
    for row in range(3):
        for col in range(3):SubElement(frame,f'R{row}{col}').text=str((1 if row==1 else -1) if row==col else 0)
    prop(props,'Color3uint8','Color3uint8',16777215);prop(props,'token','Material',272)
    for key in ['Anchored','DoubleSided','CastShadow']:prop(props,'bool',key,'true')
    for key in ['CanCollide','CanTouch','CanQuery']:prop(props,'bool',key,'false')
    prop(props,'token','CollisionFidelity',3 if spec['category']=='shore' else 1);prop(props,'token','RenderFidelity',0)
    surface=SubElement(SubElement(model[-1],'Item',{'class':'SurfaceAppearance'}),'Properties')
    prop(surface,'string','Name','MattePalette')
    for name,value in [('ColorMap',p['textureId']),('RoughnessMap','rbxassetid://105908452608029')]:SubElement(SubElement(surface,'Content',name=name),'url').text=value
path=ROOT/'src/ServerStorage/MeadowTemplates.rbxmx';path.write_bytes(tostring(xml,encoding='utf-8'))
lines=['--!strict','-- Generated by tools/finalize_meadows.py. Shared boundary vertices, no overlapping caps.','return {','\tboundary = {']
for p in catalog['boundary']:lines.append('\t\t{ x = %.8f, z = %.8f, height = %.8f },'%(p['x'],p['z'],p['height']))
lines.extend(['\t},','}'])
(ROOT/'src/ReplicatedStorage/Shared/MeadowBoundary.luau').write_text('\n'.join(lines)+'\n')
shore=json.loads((folder/'shore-layout.json').read_text())
lines=['--!strict','-- Generated layout cache. MeadowShore falls back to triangles if the layout changes.','return {','\tponds = {']
for p in shore['ponds']:lines.append('\t\t{ x = %.8f, z = %.8f, radius = %.8f, side = %d },'%(p['x'],p['z'],p['radius'],p['side']))
lines.extend(['\t},','\tstream = { x = %.8f, z0 = %.8f, z1 = %.8f, halfWidth = %.8f },'%(shore['stream']['x'],shore['stream']['z0'],shore['stream']['z1'],shore['stream']['halfWidth']),'}'])
(ROOT/'src/ReplicatedStorage/Shared/MeadowShoreLayout.luau').write_text('\n'.join(lines)+'\n')
print('Verified',len(imports),'imported meshes, size and handedness; wrote Rojo templates and boundary.')
