"""Install uploaded Arcade receipts, materials, accessory poses and crate rows."""
from pathlib import Path
import json,sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_skin_packs import pack_for
ROOT=Path(__file__).resolve().parents[1];HERE=ROOT/'assets/piggies/arcade-build-v1';SHARED=ROOT/'src/ReplicatedStorage/Shared'
specs=json.loads((HERE/'manifest.json').read_text())['skins']
active_path=HERE/'active-revisions.json'
active=json.loads(active_path.read_text()) if active_path.exists() else {}
if any(revision != 'v2' for revision in active.values()):
    raise SystemExit('Newer approved revisions are active. Use tools/install_approved_skins.py; this legacy installer would replace them with old models.')
motion=json.loads((HERE/('runtime-source-v2.json' if active else 'runtime-source.json')).read_text())
model_ids={}
def nums(v):return ', '.join(f'{x:.7g}' for x in v)
def rgb(v):return 'Color3.fromRGB('+nums(v)+')'
def vec(v):return 'Vector3.new('+nums(v)+')'
def replace_block(s,name,content,anchor):
    start='\t-- BEGIN ARCADE '+name;end='\t-- END ARCADE '+name
    if start in s:
        a=s.index(start);b=s.index(end,a)+len(end);return s[:a]+start+'\n'+content+end+s[b:]
    assert anchor in s,anchor
    return s.replace(anchor,anchor+'\n'+start+'\n'+content+end,1)
config=(SHARED/'Config.luau').read_text()
skins=[];packs=[];auras=[];access=[];animation=['-- Generated by tools/install_arcade.py from authored Blender motion.','return {']
for i,s in enumerate(specs):
    key=s['key'];tier=s['tier'];home=HERE.parent/tier/key
    receipt=json.loads((home/'roblox-uploads.json').read_text())['assets'].copy()
    if active.get(key)=='v2':
        for role,item in list(receipt.items()):
            if role.endswith('_v2'):receipt[role[:-3]]=item
        if key=='mechaplayer':
            receipt.pop('body_emissive',None);receipt.pop('trim_emissive',None)
    if 'accessories' in receipt:model_ids[key]=receipt['accessories']['assetId']
    assert all(a.get('moderationState')=='Approved' for a in receipt.values()),key
    for part in ('body','trim'):
        slots={'ColorMap':'rbxassetid://'+receipt[part+'_color']['assetId']}
        if part+'_emissive' in receipt:slots['EmissiveMaskContent']='rbxassetid://'+receipt[part+'_emissive']['assetId']
        pack=pack_for(slots,tier)
        if key=='mechaplayer' and active.get(key)=='v2':
            pack['properties']['EmissiveMaskContent']=''
            pack['properties']['EmissiveStrength']=0
        (SHARED/'SurfacePacks'/f"{key if part=='body' else key+'_trim'}.model.json").write_text(json.dumps(pack,indent=2)+'\n')
    palette=s['palette'];aura='arcade_'+key
    extras=''
    if tier!='rare':
        extras=f'\n\t\taura = "{aura}", glowEyes = '+('false' if key=='jackpot' or active.get(key)=='v2' else 'true')+f', parts = {{ Eye = {rgb([27,27,32] if key=="jackpot" or active.get(key)=="v2" else palette[1])} }},'
        auras.append(f'''\t{aura} = {{
\t\tname = "{s['name']} Sparks", texture = SPARK,
\t\tcolor = ColorSequence.new({rgb(palette[1])}, {rgb(palette[-1])}),
\t\trate = {7 if tier=='epic' else 11}, speed = NumberRange.new(0.6, 1.5), size = 0.35,
\t\tlifetime = NumberRange.new(0.8, 1.5), drag = 1.4, accel = Vector3.new(0, 1.6, 0),
\t\tspread = 18, rotSpeed = 20, inOut = "Outward",
\t}},''')
    skins.append(f'''\t{key} = {{
\t\tname = "{s['name']}", order = {200+i}, chest = "og", collection = "arcade", rarity = "{tier}",
\t\tbody = {rgb(palette[0])}, trim = {rgb(palette[1])},
\t\tmaterial = Enum.Material.SmoothPlastic, transparency = 0, surface = "{key}",{extras}
\t}},''')
    packs.append(f'\t{key} = {{ name = "{s["name"]}", template = "{key}", trimTemplate = "{key}_trim" }},')
    if key not in motion:continue
    imports=json.loads((HERE/f'imported-{key}{"-v2" if active.get(key)=="v2" else ""}.json').read_text());assert len(imports)==len(motion[key])
    access.append(f'\t{key} = {{');animation.append(f'\t{key} = {{')
    for imported in imports:
        name=imported['name'];p=motion[key][name]
        center=[x/100 for x in imported['cf'][:3]];size=[x/100 for x in imported['size']]
        assert max(abs(x-y) for x,y in zip(center,p['center']))<.002,(key,name,'center')
        assert max(abs(x-y) for x,y in zip(size,p['size']))<.002,(key,name,'size')
        texture=imported.get('sa') or imported.get('texture')
        material='Neon' if p['emission']>.4 else 'Metal' if p['metallic']>.4 else 'SmoothPlastic'
        access.append(f'\t\t{{ part = "{name}", id = "{imported["id"]}", offset = {vec(center)}, size = {vec(size)}, colour = {rgb([255,255,255] if texture else p["color"])}, material = Enum.Material.{material}'+(f', surfaceTemplate = "arcade_{key}_{name}"' if texture else '')+' },')
        if texture:
            (SHARED/'SurfacePacks'/f'arcade_{key}_{name}.model.json').write_text(json.dumps(pack_for({'ColorMap':texture},tier),indent=2)+'\n')
        if p['samples']:
            animation.append(f'\t\t["{name}"] = {{')
            for sample in p['samples']:animation.append('\t\t\t{'+nums(sample)+'},')
            animation.append('\t\t},')
    access.append('\t},');animation.append('\t},')
animation.append('}')
(SHARED/'ArcadeMotionData.luau').write_text('\n'.join(animation)+'\n')
for name,rows,anchor in [('SKINS',skins,'Config.SKINS = {'),('PACKS',packs,'Config.SURFACE_PACKS = {'),('AURAS',auras,'Config.SKIN_AURAS = {'),('ACCESSORIES',access,'Config.SKIN_ACCESSORIES = {')]:config=replace_block(config,name,'\n'.join(rows)+'\n',anchor)
# THE PIGGY CRATES MERGED (designer, 2026-09-23): Arcade skins are tagged to
# the one piggy shelf (`chest = "og"`) and keep their theme as `collection`.
# So this installer writes NO crate rows and NO section any more -- the
# markers stay, empty, so a rerun cannot put the old Arcade crates back.
crates=''
model_rows=''.join(f'\t{k} = "{model_ids[k]}",\n' for k in motion)
config=replace_block(config,'MODELS',model_rows,'Config.SKIN_ACCESSORY_MODELS = {')
config=replace_block(config,'CRATES',crates,'Config.CHESTS = {')
config=replace_block(config,'SECTIONS','','Config.CRATE_SECTIONS = {')
(SHARED/'Config.luau').write_text(config)
print(f'Installed {len(specs)} skins, {sum(len(v) for v in motion.values())} accessories, 6 auras and authored motion.')
